FROM	nginx:1.25

# Remove default configuration
RUN		rm /etc/nginx/conf.d/default.conf

# Copy custom nginx configuration
COPY	nginx.conf /etc/nginx/conf.d/

# Define working directory
RUN		mkdir /home/app
ENV		APP_HOME=/home/app/web
RUN		mkdir $APP_HOME
WORKDIR	$APP_HOME

# Create static and media files directory
RUN		mkdir $APP_HOME/staticfiles
RUN		mkdir $APP_HOME/mediafiles

# Update permissions of directories to Nginx
RUN		chown -R nginx:nginx $APP_HOME/staticfiles $APP_HOME/mediafiles
RUN		chmod -R 755 $APP_HOME/staticfiles $APP_HOME/mediafiles

# Change user directive in Nginx configuration
RUN		sed -i 's/user  nginx;/user  root;/' /etc/nginx/nginx.conf
